In [ ]:
## relational data 
## structure data 
## real world --> structure format -> use(analysis and calculation)

In [ ]:
## Pandas help with analysis and calculation 

# Use Case
    # 1. data manipulation
    # 2. Analysis

# Raw Data --> Process data(Python,numpy,pandas) --> Clean Data  --> Machine Learning(specific format)  -->

In [38]:
import pandas as pd
import numpy as np

In [ ]:
## array, list , dict, tuple, set, matrix, vector

## Series in pandas
    IT is labeled as one dimensional array

In [ ]:
s1 = pd.Series([10,20,30,40,50,60]) ## without index it will auto increment 
print(s1)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [5]:
s1 = pd.Series([10,20,30,40,50,60],index=['a', 'b', 'c', 'd', 'e', 'f'])
print(s1)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [6]:
s1 = pd.Series([10,20,30,40,50,60],index=['a', 'b', 'c', 'd', 'e', 'f'],name="Scores")
print(s1)

a    10
b    20
c    30
d    40
e    50
f    60
Name: Scores, dtype: int64

In [9]:
## Create series from dict

data  = {'a': 10, 'b': 20, 'c': 30, 'd': 40}
d1 = pd.Series(data)
print(d1)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
## 2D, 3D -->[[1,2],[2,3]] --> flatten --> np.flatten() --> []

In [14]:
print(s1.index)
print(s1.values)
print(s1.dtype)
print(s1.name)
print(s1.shape)

## dict --> keys and values

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')
[10 20 30 40 50 60]
int64
Scores
(6,)

### Series Indexing and Slicing

In [15]:
s1 = pd.Series([10,20,30,40,50,60],index=['a', 'b', 'c', 'd', 'e', 'f'],name="Scores")
print(s1)

a    10
b    20
c    30
d    40
e    50
f    60
Name: Scores, dtype: int64

In [17]:
print(s1.values[0])  ## positional index

10

In [21]:
print(s1.loc['a']) # indexing 

# print(s1.loc[0]) # indexing

10

In [ ]:
print(s1.iloc[0])  ## Posistional Indexing

10

In [24]:
print(s1.loc[['a','b']]) # indexing

a    10
b    20
Name: Scores, dtype: int64

In [25]:
print(s1.iloc[[0,1]])

a    10
b    20
Name: Scores, dtype: int64

In [27]:
print(s1.iloc[0:3])  ## Positional indexing (exclusive)

a    10
b    20
c    30
Name: Scores, dtype: int64

In [28]:
#Creating series from dict 
data = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 0 :100, 1: 101, 2: 400, 6:700}
s2 = pd.Series(data ,name="SCores")

In [30]:
s2.loc[0:2]  ## inclusive

0    100
1    101
2    400
Name: SCores, dtype: int64

In [31]:
## Slicing 
    ## loc [start, end] : end is inclusive 
    ## iloc [start, end] : end is exclusive

### Data frames

In [32]:
data = {
    'Name' : ['Aswathi','Sidharth','Arooshi','Vivek'],
    'Age' : [22,26,22,25],
    'City' : ['Bangaluru','California','Rajasthan','Italy']
}

In [34]:
df = pd.DataFrame(data)
print(df)

       Name  Age        City
0   Aswathi   22   Bangaluru
1  Sidharth   26  California
2   Arooshi   22   Rajasthan
3     Vivek   25       Italy

In [36]:
data_1= [
    {'Name': 'Aswathi', 'Age':22 ,'City': 'Bangaluru'},
    {'Name': 'Sidharth ', 'Age':26 ,'City': 'California'},
    {'Name': 'Arooshi', 'Age':22 ,'City': 'Rajasthan'},
   {'Name': 'Vivek', 'Age':25 ,'City': 'Italy'},
]

In [37]:
df_1 = pd.DataFrame(data_1)
print(df_1)

        Name  Age        City
0    Aswathi   22   Bangaluru
1  Sidharth    26  California
2    Arooshi   22   Rajasthan
3      Vivek   25       Italy

In [39]:
arr_data = np.array([[1,2],[3,4],[5,6]])

In [40]:
df_2 = pd.DataFrame(arr_data)
print(df_2)

   0  1
0  1  2
1  3  4
2  5  6

In [41]:
df_2 = pd.DataFrame(arr_data, columns = ['A','B'])
print(df_2)

   A  B
0  1  2
1  3  4
2  5  6

### Accessing the Values

In [42]:
data = {
    'Name' : ['Aswathi','Sidharth','Arooshi','Vivek'],
    'Age' : [22,26,22,25],
    'City' : ['Bangaluru','California','Rajasthan','Italy']
}
df_4 =pd.DataFrame(data)

In [47]:
print(df_4)

       Name  Age        City
0   Aswathi   22   Bangaluru
1  Sidharth   26  California
2   Arooshi   22   Rajasthan
3     Vivek   25       Italy

In [43]:
type(df_4)

pandas.core.frame.DataFrame

In [50]:
print(df_4['Name'])
print('='*40)
print(df_4[['Name','Age']])
print('='*40)
print(df_4.loc[0])
print('='*40)
print(df_4.loc[0:1])  ## inclusive
print('='*40)
print(df_4.iloc[0])
print('='*40)
print(df_4.iloc[0:1]) ## exclusive

0     Aswathi
1    Sidharth
2     Arooshi
3       Vivek
Name: Name, dtype: object
========================================
       Name  Age
0   Aswathi   22
1  Sidharth   26
2   Arooshi   22
3     Vivek   25
========================================
Name      Aswathi
Age            22
City    Bangaluru
Name: 0, dtype: object
========================================
       Name  Age        City
0   Aswathi   22   Bangaluru
1  Sidharth   26  California
========================================
Name      Aswathi
Age            22
City    Bangaluru
Name: 0, dtype: object
========================================
      Name  Age       City
0  Aswathi   22  Bangaluru

### Working with Real Dataset

In [52]:
titanic_dataset = "Titanic-Dataset.csv"

In [53]:
df = pd.read_csv(titanic_dataset) ## raw data

In [59]:
## Preview of the dataframe
# first 5 rows
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [58]:
# last 5 rows
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [60]:
df.shape

(891, 12)

In [61]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [62]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [64]:
df[['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [66]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [68]:
df.loc[0,'Name']  # Name of the passenger at index 0

'Braund, Mr. Owen Harris'

In [69]:
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [70]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [71]:
df.iloc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [72]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.iloc[0,3]  ## Positional index

'Braund, Mr. Owen Harris'

## Conditional Selection

In [81]:
## get all the rows where person age is greater than 70
## df[condition]

df[df['Age']>70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [82]:
Senior_Passanger = df[df['Age']>70]
Senior_Passanger.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [87]:
## get all the females who survived 

Female_Sur=df[(df['Sex'] == 'female') & (df['Survived'] == 1)]
Female_Sur.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [90]:
female_Pasanger = df[(df['Sex'] == 'female') & (df['Survived'] == 1)][['Name','Age']]
female_Pasanger.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [95]:
## total no of survivers
survived = len(df[df['Survived']==1])
nonsurvived = len(df[df['Survived']==0])
print(survived)
Total = nonsurvived+survived

342

In [96]:
survived/Total

0.3838383838383838

In [97]:
nonsurvived/Total

0.6161616161616161