In [1]:
import numpy as np
import pandas as pd

In [ ]:
irirs_dataset_github_url = "https://gist.github.com/curran/a08a1080b88344b0c8a7"

In [7]:
df  = pd.read_csv('Titanic-Dataset.csv')

In [11]:
a = df[(df['Sex']=='female' ) & (df['Survived']==1)].head()
print(a)

   PassengerId  Survived  Pclass  \
1            2         1       1
2            3         1       3
3            4         1       1
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

In [12]:
female_survivors_subset = df[(df['Sex'] == 'female') & (df['Survived'] == 1)][['Name','Age']]
print(female_survivors_subset)

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [20]:
female_survivors_subset_loc = df.loc[((df['Sex'] == 'female') & (df['Survived'] == 1)),['Name','Age']]
female_survivors_subset_loc.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [21]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [22]:
df.loc[0,['Cabin']]

Cabin    NaN
Name: 0, dtype: object

In [23]:
# [] ---> ## list ,array

In [24]:
def add(a):
    print(a[0] + a[1])

In [25]:
add([2,4])

6

In [27]:
### Slicing Rows and Columns 

df.loc[0:4,['Name','Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
## # rows and first 2 columns

## --> numbers of index
df.iloc[0:3,0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [31]:
# first 3 rows and selected codulmns by index
## ----> column 1,3
df.iloc[0:3,[1,3]]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina

In [32]:
df.iloc[0:3,[3,1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [37]:
df.loc[0:2,['Name','Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [38]:
df.loc[0:2,['Survived' ,'Name']]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina

In [ ]:
## when we use iloc we allways get a copy  not a refrence
## when we use iloc we allways get  refrence or a view

In [40]:
## df.loc[Condition].copy()

In [46]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [44]:
subset = df[df['Sex'] == 'male']

In [ ]:
# SettingWithCopyWarning: 
subset['Age'] = subset['Age'] + 1
print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

C:\Users\aswat\AppData\Local\Temp\ipykernel_18888\1163773135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['Age'] = subset['Age'] + 1

In [49]:
subset.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.25,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.05,NaN,S

In [50]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [47]:
subset = df[df['Sex'] == 'male'].copy()

In [ ]:
## No warning 
subset['Age'] = subset['Age'] + 1
print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

In [ ]:
# iloc  ---> copy
# loc  ----> may be view
# df  -----> may be view

# df

# df.copy()

In [53]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [61]:
df_by_name = df.set_index('Name')
df_by_name.head(2)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [62]:
print(df_by_name.loc['Allen, Mr. William Henry'])

PassengerId         5
Survived            0
Pclass              3
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         373450
Fare             8.05
Cabin             NaN
Embarked            S
Name: Allen, Mr. William Henry, dtype: object

In [86]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [91]:
df_by_name = df.set_index('Name')

In [92]:
df_by_name.head(2)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [93]:
df_by_name = df_by_name.reset_index()

In [94]:
df_by_name.head(2)

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [98]:
df_by_name.reset_index(inplace=True)

In [99]:
df_by_name.head(2)

,level_0,index,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [102]:
df_by_name = df.set_index('Name')
df_by_name = df_by_name.reset_index()
df_by_name.head(2)

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [101]:
df_by_name = df.set_index('Name')
df_by_name.reset_index(inplace=True)
df_by_name.head(2)

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [122]:
## Reindex
sales_jan  =pd.DataFrame({
    'Sales':[250,400,300,450]
}, index=['Store_A','Store_B','Store_C','Store_D'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300
Store_D    450

In [123]:
sales_feb  =pd.DataFrame({
    'Sales':[260,310]
}, index=['Store_A','Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    310

In [124]:
common_index = sales_jan.index

In [109]:
sales_feb_aligned  = sales_feb.reindex(common_index)

In [110]:
sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [111]:
Sales_diff= sales_feb_aligned['Sales'] - sales_jan['Sales']

In [112]:
Sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [115]:
sales_feb_aligned = sales_feb.reindex(common_index,fill_value=0)
sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [116]:
Sales_diff= sales_feb_aligned['Sales'] - sales_jan['Sales']
Sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

In [118]:
common_index_List = list(set(list(sales_jan.index) + list(sales_feb.index)))
common_index_List

['Store_A', 'Store_C', 'Store_B']

In [126]:
sales_feb_new_aligned = sales_feb.reindex(common_index,fill_value=0)
sales_feb_new_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310
Store_D      0

In [128]:
sales_jan_aligned = sales_jan.reindex(common_index,fill_value=0)
sales_jan_aligned

         Sales
Store_A    250
Store_B    400
Store_C    300
Store_D    450

In [129]:
to_cheack  = 'Store_C'
print(sales_feb_new_aligned.loc[to_cheack])
print(sales_jan_aligned.loc[to_cheack])

Sales    310
Name: Store_C, dtype: int64
Sales    300
Name: Store_C, dtype: int64

In [ ]:
# For Columns

In [134]:
source_a = pd.DataFrame({
    'Product': ['Laptop','Tablet','iPhone'],
    'Price': [1000, 500, 8000],
    'Stock': [30, 50, 100]
})
source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2  iPhone   8000    100

In [135]:
source_b = pd.DataFrame({
    'Price': [9800, 520, 8040],
    'Product': ['Laptop','Tablet','iPhone']
})
source_b

   Price Product
0   9800  Laptop
1    520  Tablet
2   8040  iPhone

In [136]:
aligned_b = source_b.reindex(columns=source_a.columns,fill_value = 0)
aligned_b

  Product  Price  Stock
0  Laptop   9800      0
1  Tablet    520      0
2  iPhone   8040      0

### Iteration in Pandas

In [149]:
df = pd.DataFrame({
    'Name' : ['Aswathi','Sidharth','Arooshi'],
    'Age'  : [23, 27, 23],
    'City' : ['New York', 'Los Angelas', 'Manchaester']
})

In [150]:
for index, row in df.iterrows():
    print(row,end='\n\n')

Name     Aswathi
Age           23
City    New York
Name: 0, dtype: object

Name       Sidharth
Age              27
City    Los Angelas
Name: 1, dtype: object

Name        Arooshi
Age              23
City    Manchaester
Name: 2, dtype: object

In [151]:
for index, row in df.iterrows():
    print(f"{index} : {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

0 : Aswathi lives in New York and is 23 years old.
1 : Sidharth lives in Los Angelas and is 27 years old.
2 : Arooshi lives in Manchaester and is 23 years old.

In [153]:
for row in df.iterrows():
    print(row)

(0, Name     Aswathi
Age           23
City    New York
Name: 0, dtype: object)
(1, Name       Sidharth
Age              27
City    Los Angelas
Name: 1, dtype: object)
(2, Name        Arooshi
Age              23
City    Manchaester
Name: 2, dtype: object)

In [154]:
for row in df.itertuples():
    print(row.Name)

Aswathi
Sidharth
Arooshi

In [155]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [158]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [160]:
for col in df.columns:
    print(f" Columns : {col}")
    print(df[col].values , end='\n\n')

 Columns : Name
['Aswathi' 'Sidharth' 'Arooshi']

 Columns : Age
[23 27 23]

 Columns : City
['New York' 'Los Angelas' 'Manchaester']

In [161]:
## condition  based  column creation using custom logic

In [162]:
df.head()

       Name  Age         City
0   Aswathi   23     New York
1  Sidharth   27  Los Angelas
2   Arooshi   23  Manchaester

In [ ]:
# if >=30 , senior else younger

In [164]:
values = []

for idx , row in df.iterrows():
    if row['Age'] <30:
        values.append('Young')
    else:
        values.append('Senior')

df['Category'] = values

In [165]:
df.head()

       Name  Age         City Category
0   Aswathi   23     New York    Young
1  Sidharth   27  Los Angelas    Young
2   Arooshi   23  Manchaester    Young

In [166]:
# Vectorized using apply

In [ ]:
df = pd.DataFrame({
    'Name' : ['Aswathi','Sidharth','Arooshi'],
    'Age'  : [23, 27, 23],
    'City' : ['New York', 'Los Angelas', 'Manchaester']
})

In [167]:
df['Category'] = df['Age'].apply(lambda age: 'Young' if age < 30 else 'Senior')

In [168]:
df.head

<bound method NDFrame.head of        Name  Age         City Category
0   Aswathi   23     New York    Young
1  Sidharth   27  Los Angelas    Young
2   Arooshi   23  Manchaester    Young>

In [ ]:
# iterrows < itertuples < apply

### Sort

In [169]:
# 1. sort_values  ----> data values
# 2. sort_index  ----> rows/ column

In [170]:
df = pd.read_csv('Titanic-Dataset.csv')

In [172]:
sorted_df = df.sort_values(by='Age')
sorted_df[['Name','Age']].head(5)

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
469    Baclini, Miss. Helene Barbara  0.75
644           Baclini, Miss. Eugenie  0.75
78     Caldwell, Master. Alden Gates  0.83

In [173]:
sorted_df[['Name', 'Age']].tail(5)

                                         Name  Age
859                          Razi, Mr. Raihed  NaN
863         Sage, Miss. Dorothy Edith "Dolly"  NaN
868               van Melkebeke, Mr. Philemon  NaN
878                        Laleff, Mr. Kristo  NaN
888  Johnston, Miss. Catherine Helen "Carrie"  NaN

In [175]:
sorted_df.loc[0:100,['Name','Age']]

                                      Name   Age
0                  Braund, Mr. Owen Harris  22.0
882           Dahlberg, Miss. Gerda Ulrika  22.0
833                 Augustsson, Mr. Albert  23.0
658           Eitemiller, Mr. George Floyd  23.0
88              Fortune, Miss. Mabel Helen  23.0
..                                     ...   ...
874  Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
848                      Harper, Rev. John  28.0
399       Trout, Mrs. William H (Jessie L)  28.0
392           Gustafsson, Mr. Johan Birger  28.0
100                Petranec, Miss. Matilda  28.0

[114 rows x 2 columns]

In [176]:
print(df['Age'].dtype)

float64

In [ ]:
# df['Age'] = df['Age'].astype('int64')   ### Cannot convert non-finite values (NA or inf) to integer

In [178]:
df['Age'] = df['Age'].fillna(0).astype('int64')

In [179]:
print(df['Age'].dtype)

int64

In [181]:
print(sorted_df[['Name','Age']].head(20))

                                  Name  Age
863  Sage, Miss. Dorothy Edith "Dolly"    0
711                 Klaber, Mr. Herman    0
718                McEvoy, Mr. Michael    0
229            Lefebre, Miss. Mathilde    0
727           Mannion, Miss. Margareth    0
235       Harknett, Miss. Alice Phoebe    0
732               Knight, Mr. Robert J    0
738                 Ivanoff, Mr. Kanio    0
95         Shorney, Mr. Charles Joseph    0
740        Hawksford, Mr. Walter James    0
240              Zabour, Miss. Thamine    0
241     Murphy, Miss. Katherine "Kate"    0
755          Hamalainen, Master. Viljo    0
760                 Garfirth, Mr. John    0
766          Brewe, Dr. Arthur Jackson    0
768                Moran, Mr. Daniel J    0
793           Hoyt, Mr. William Fisher    0
250             Reed, Mr. James George    0
803    Thomas, Master. Assad Alexander    0
76                   Staneff, Mr. Ivan    0

In [182]:
sorted_df = df.sort_values(by='Age')
print(sorted_df[['Name','Age']].tail(20))

                                          Name  Age
625                      Sutton, Mr. Frederick   61
570                         Harris, Mr. George   62
555                         Wright, Mr. George   62
252                  Stead, Mr. William Thomas   62
829  Stone, Mrs. George Nelson (Martha Evelyn)   62
275          Andrews, Miss. Kornelia Theodosia   63
483                     Turkula, Mrs. (Hedwig)   63
545               Nicholson, Mr. Arthur Ernest   64
438                          Fortune, Mr. Mark   64
54              Ostby, Mr. Engelhart Cornelius   65
456                  Millet, Mr. Francis Davis   65
280                           Duane, Mr. Frank   65
33                       Wheadon, Mr. Edward H   66
116                       Connors, Mr. Patrick   70
672                Mitchell, Mr. Henry Michael   70
745               Crosby, Capt. Edward Gifford   70
96                   Goldschmidt, Mr. George B   71
493                    Artagaveytia, Mr. Ramon   71
851                        Svensson, Mr. Johan   74
630       Barkworth, Mr. Algernon Henry Wilson   80

In [183]:
# sort by multiple columns

In [184]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [187]:
df_sorted1 = df.sort_values(by=['Pclass', 'Fare']) # ascending order

In [188]:
df_sorted1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
263,264,0,1,"Harrison, Mr. William",male,40,0,0,112059,0.0,B94,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,0,0,0,112052,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,0,0,0,112058,0.0,B102,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38,0,0,19972,0.0,NaN,S

In [189]:
df_sorted = df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False]) # ascending order

In [190]:
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S

## Sorted Index

In [191]:
df_sorted.to_csv("a.csv")

In [192]:
# sort_index

# axis = 0 # rows
# axis = 1 # column

In [198]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [199]:
df_sort_2 = df.set_index('PassengerId')

In [200]:
df_sorted_by_index = df_sort_2.sort_index(axis=0)

In [201]:
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [203]:
df_sorted_by_index = df_sort_2.sort_index(axis=0, ascending=False)
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.00,C148,C
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.45,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.00,B42,S
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.00,NaN,S

In [206]:
df_sort_2.sort_index(axis=0, ascending=False,inplace=True)
df_sort_2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,NaN,Q
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.4500,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S

# sorting columns alphabets

In [204]:
df_sorted_cols = df.sort_index(axis=1)
df_sorted_cols.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

# Changing Column order in Pandas

In [207]:
df = pd.read_csv('Titanic-Dataset.csv')

In [214]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [208]:
new_order = ['Name', 'Sex', 'Age', 'Pclass', 'Fare', 'Survived']

In [209]:
df_reordered = df[new_order]
print(df_reordered.head())

                                                Name     Sex   Age  Pclass  \
0                            Braund, Mr. Owen Harris    male  22.0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1
2                             Heikkinen, Miss. Laina  female  26.0       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1
4                           Allen, Mr. William Henry    male  35.0       3

      Fare  Survived
0   7.2500         0
1  71.2833         1
2   7.9250         1
3  53.1000         1
4   8.0500         0

In [210]:
sorted(df.columns)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [211]:
df_reordered = df[sorted(df.columns)]

df_reordered.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22.0,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38.0,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26.0,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35.0,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35.0,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

# working with text data in pandas

In [212]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [213]:
print(df[['Name', 'Sex', 'Cabin']].head(3))

                                                Name     Sex Cabin
0                            Braund, Mr. Owen Harris    male   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   C85
2                             Heikkinen, Miss. Laina  female   NaN

In [215]:
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [216]:
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [217]:
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [218]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [219]:
df['Name'].str.replace("Mr.", "Sir", regex=False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: object

In [220]:
# p.s -> replace every thing with brackets in it

# (abc)
# (abc abc)
# (Abc dasdass dsds dsdsw dsds dswds)
# pattern-1 , start - (, words of any length, end - )
# pattern-2 , start - (, end - ), words of any length,

In [221]:
df['Name'].str.replace(r"\(.*\)", "", regex=True).head()

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: object

# Extract with Regex

In [222]:
df['Title'] = df['Name'].str.extract(r'(\(.*\))', expand=False)

In [223]:
df['Title']

0                           NaN
1      (Florence Briggs Thayer)
2                           NaN
3               (Lily May Peel)
4                           NaN
                 ...
886                         NaN
887                         NaN
888                         NaN
889                         NaN
890                         NaN
Name: Title, Length: 891, dtype: object

In [224]:
type(df['Name'].str.extract(r'(\(.*\))', expand=True))

pandas.core.frame.DataFrame

In [225]:
type(df['Name'].str.extract(r'(\(.*\))', expand=False))

pandas.core.series.Series

# Split and Access Elements

In [226]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [232]:
df['Name'].str.split(",", expand=False)[0]

['Braund', ' Mr. Owen Harris']

In [227]:
df['Name'].str.split(",", expand=True)[0]

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: 0, Length: 891, dtype: object

In [233]:
df['Name'].str.split()[0] # all white space

['Braund,', 'Mr.', 'Owen', 'Harris']

In [228]:
df['Name'].str.split(expand=True)[0] # all white space

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: 0, Length: 891, dtype: object

In [229]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [230]:
df['Name'].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [231]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

# Find position of substring

In [234]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [235]:
# Count passengers with “Miss” in name
count = df['Name'].str.contains("Miss").sum()
print("Number of 'Miss':", count)

Number of 'Miss': 182